#!/usr/bin/with-contenv bash

if [ -n "$MJPEG_STREAMER_INPUT" ]; then
  echo "Deprecation warning: the environment variable '$MJPEG_STREAMER_INPUT' was renamed to '$MJPG_STREAMER_INPUT'"
  MJPG_STREAMER_INPUT=$MJPEG_STREAMER_INPUT
fi

if ! echo "$MJPG_STREAMER_INPUT" | grep -q "..so."; then
  MJPG_STREAMER_INPUT="input_uvc.so $MJPG_STREAMER_INPUT"
fi

IFS=',' read -ra CAMERA_DEVS <<<"$CAMERA_DEV"
CAMERA_ARGS=""
for CAMERA in ${CAMERA_DEVS[*]}; do
  CAMERA_ARGS="$CAMERA_ARGS -i \"/usr/local/lib/mjpg-streamer/${MJPG_STREAMER_INPUT} -d ${CAMERA}\""
done

eval "exec mjpg_streamer $CAMERA_ARGS -o '/usr/local/lib/mjpg-streamer/output_http.so -w /usr/local/share/mjpg-streamer/www -p 8080'"
