#!/bin/sh

exec /mjpg/mjpg-streamer-master/mjpg-streamer-experimental/mjpg_streamer \
  -i "/usr/local/lib/mjpg-streamer/input_uvc.so -y -n -r 640x480 -d /dev/video0" \
  -o "/usr/local/lib/mjpg-streamer/output_http.so -w /usr/local/share/mjpg-streamer/www -p 8080"
