name: deploy latest with python2.7

on:
  push:
    branches: [ master ]

env:
  DOCKER_CLI_EXPERIMENTAL: "enabled"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: setup
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run Buildx
        id: buildx
        run: |
          echo ${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_USERNAME}} --password-stdin
          make buildx-push
