#!/usr/bin/with-contenv bash

: "${AUTOMIGRATE:=false}"

if $AUTOMIGRATE; then
  echo "AUTOMIGATE enabled...."
  if [[ -d "/octoprint/data" ]] || [[ -f "/octoprint/config.yaml" ]]; then
    echo "octoprint-docker v2 directory structure detected...."
    echo "migrating to octoprint-docker v3 directory structure..."
    mkdir -p /octoprint/octoprint /octoprint/plugins
    mv /octoprint/* /octoprint/octoprint

    [[ -d "/octoprint/octoprint/plugins/bin" ]] && mv /octoprint/octoprint/plugins/bin $PYTHONUSERBASE
    [[ -d "/octoprint/octoprint/plugins/lib" ]] && mv /octoprint/octoprint/plugins/lib $PYTHONUSERBASE
    [[ -d "/octoprint/octoprint/plugins/include" ]] && mv /octoprint/octoprint/plugins/include $PYTHONUSERBASE
    [[ -d "/octoprint/octoprint/plugins/local" ]] && mv /octoprint/octoprint/plugins/local $PYTHONUSERBASE
    [[ -d "/octoprint/octoprint/plugins/share" ]] && mv /octoprint/octoprint/plugins/share $PYTHONUSERBASE

    echo "v2 -> v3 octoprint-docker auto-migration migration complete!"
  fi

  if [[ -d "/root/.octoprint" ]]; then
    echo "octoprint-docker v1 directory structure detected...."
    echo "migrating to octoprint-docker v3 directory structure..."

    mkdir -p /octoprint/octoprint /octoprint/plugins
    mv /root/.octoprint/* /octoprint/octoprint

    [[ -d "/octoprint/octoprint/plugins/bin" ]] && mv /octoprint/octoprint/plugins/bin $PYTHONUSERBASE
    [[ -d "/octoprint/octoprint/plugins/lib" ]] && mv /octoprint/octoprint/plugins/lib $PYTHONUSERBASE
    [[ -d "/octoprint/octoprint/plugins/include" ]] && mv /octoprint/octoprint/plugins/include $PYTHONUSERBASE
    [[ -d "/octoprint/octoprint/plugins/local" ]] && mv /octoprint/octoprint/plugins/local $PYTHONUSERBASE
    [[ -d "/octoprint/octoprint/plugins/share" ]] && mv /octoprint/octoprint/plugins/share $PYTHONUSERBASE

    echo "v1 -> v3 octoprint-docker auto-migration complete!"
  fi

fi
